### ISSUE TITLE
size mismatch for word_embeddings.weight

### ISSUE THREAD

**Issue by AnddyWang** [yangjianxin1/LEBERT-NER-Chinese#6]
2022-06-24 11:31:30.005 | INFO     | processors.processor:get_test_data:75 - len of test data:1602
Traceback (most recent call last):
  File "test.py", line 476, in <module>
    main(args)
  File "test.py", line 442, in main
    model = MODEL_CLASS[args.model_class].from_pretrained(args.output_path, config=config).to(args.device)
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_utils.py", line 972, in from_pretrained
    model.__class__.__name__, "\n\t".join(error_msgs)
RuntimeError: Error(s) in loading state_dict for LEBertCrfForNer:
        size mismatch for word_embeddings.weight: copying a param with shape torch.Size([29061, 200]) from checkpoint, the shape in current model is torch.Size([29137, 200]).

预测时，报这个异常，有大佬遇到过么

**Comment by Mosquito0352** [comment]
训练可以跑通么

**Comment by Mosquito0352** [comment]
> 2022-06-24 11:31:30.005 | INFO | processors.processor:get_test_data:75 - len of test data:1602 Traceback (most recent call last): File "test.py", line 476, in main(args) File "test.py", line 442, in main model = MODEL_CLASS[args.model_class].from_pretrained(args.output_path, config=config).to(args.device) File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_utils.py", line 972, in from_pretrained model.**class**.**name**, "\n\t".join(error_msgs) RuntimeError: Error(s) in loading state_dict for LEBertCrfForNer: size mismatch for word_embeddings.weight: copying a param with shape torch.Size([29061, 200]) from checkpoint, the shape in current model is torch.Size([29137, 200]).
> 
> 预测时，报这个异常，有大佬遇到过么


> 2022-06-24 11:31:30.005 | INFO | processors.processor:get_test_data:75 - len of test data:1602 Traceback (most recent call last): File "test.py", line 476, in main(args) File "test.py", line 442, in main model = MODEL_CLASS[args.model_class].from_pretrained(args.output_path, config=config).to(args.device) File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_utils.py", line 972, in from_pretrained model.**class**.**name**, "\n\t".join(error_msgs) RuntimeError: Error(s) in loading state_dict for LEBertCrfForNer: size mismatch for word_embeddings.weight: copying a param with shape torch.Size([29061, 200]) from checkpoint, the shape in current model is torch.Size([29137, 200]).
> 
> 预测时，报这个异常，有大佬遇到过么

可以看下预测的代码么？
